<a href="https://colab.research.google.com/github/karandeep1729/Data-Analysis-and-Statistics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numerical Python

Numpy is a python library which allows us to work with arrays.
Numpy allows us to do mathematics operation in our program

Numpy was created by Tracis Oliphat in year 2005



Numpy arrays are upto 50x faster than your list

In [ ]:
import numpy as np    #Alias

In [ ]:
# help(numpy)

In [ ]:
#Let's create numpy array
var = np.array([100,200,300,400,500])

In [ ]:
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
a = np.array([10,20,30,34.5,True])
a

array([10. , 20. , 30. , 34.5,  1. ])

In [ ]:
f_arr = np.array([34.5,65.8,42.1,12.8,45.7])

In [ ]:
f_arr
f_arr.ndim

1

In [ ]:
print(arr,"Dimensions of my int array",arr.ndim)   #ndim function is used to check the dimensions of array

[10 20 30 40 50] Dimensions of my int array 1


In [ ]:
# How to create 0D array
zero_arr = np.array(32)  #Scaler Value

In [ ]:
zero_arr

array(32)

In [ ]:
zero_arr.ndim

0

# Number of [] square bracktes = Dimensions of your array

In [ ]:
dummy_arr = np.array([[[[[[[[[[]]]]]]]]]])
dummy_arr.ndim    #ndim is the pre defined functions used to check your dimensions of your array

10

In [ ]:
new_arr = np.array([[[1,2,3],[5,7,9],[10,20,30]],[[15,25,35],[55,57,59],[150,250,305]]])

In [ ]:
print(new_arr)
print(new_arr.ndim,"D array")

[[[  1   2   3]
  [  5   7   9]
  [ 10  20  30]]

 [[ 15  25  35]
  [ 55  57  59]
  [150 250 305]]]
3 D array


In [ ]:
print(new_arr.shape)   #Shape function used to check the size of your array. It gives the output as (Rows, columns)

(3, 3)


In [ ]:
#If you will merge two 2-D arrays you can create a 3d Array

In [ ]:
demo = np.array([[[4,5,6],[1,2,3]],[[14,15,61],[11,21,31]]])
print(demo)
demo.shape


[[[ 4  5  6]
  [ 1  2  3]]

 [[14 15 61]
  [11 21 31]]]


(2, 2, 3)

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[15,20,25]]])

In [ ]:
print(arr)
print(arr.ndim,"D array")
print(arr.shape)           #Shape function tells us Number of 2d arrays, number of rows and number of columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [15 20 25]]]
3 D array
(2, 2, 3)


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[15,20,25]],[[100,200,300],[600,700,800]]])

In [ ]:
print(arr)
print(arr.ndim)
print(arr.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 15  20  25]]

 [[100 200 300]
  [600 700 800]]]
3
(3, 2, 3)


In [ ]:
arr1 = np.array([[[1.04,2.05],[8.9,7.9]],[[1.3,45.3],[34.2,45.8]]])

In [ ]:
arr1

array([[[ 1.04,  2.05],
        [ 8.9 ,  7.9 ]],

       [[ 1.3 , 45.3 ],
        [34.2 , 45.8 ]]])

In [ ]:
arr = np.array([[10,20,50], [40,50,60], [100,200,500]])    # So if you merge two  1-dimensional arrays together we can create a 2-D array.

In [ ]:
arr

array([[ 10,  20,  50],
       [ 40,  50,  60],
       [100, 200, 500]])

In [ ]:
arr.ndim

2

In [ ]:
new_arr = np.array([[[10,20,30],[40,50,60]],[[32,12,35],[48,54,69]]])
new_arr.ndim

3

In [ ]:
arr = np.array([[['a','b','c'],['d','e','f']], [['g','h','i'],['j','k','l']]])
arr.ndim

3

In [ ]:
arr = np.array([[10, 15, 20, 25], [30, 35, 40, 13],[16, 18, 20, 28]])
print(arr, arr.ndim)

[[10 15 20 25]
 [30 35 40 13]
 [16 18 20 28]] 2


In [ ]:
arr[1:3,:3:2]
# #arr[1,3]
# #arr[1,2]
# arr[0:3,-1]

array([[30, 40],
       [16, 20]])

In [ ]:
new_arr = np.array([[[10,20,25],[40,50,60]],[[1,9,5],[4,5,6]],[[16,96,65],[64,65,66]]])

print(new_arr,new_arr.ndim)

[[[10 20 25]
  [40 50 60]]

 [[ 1  9  5]
  [ 4  5  6]]

 [[16 96 65]
  [64 65 66]]] 3


In [ ]:
new_arr[0:2,0,1:3]

array([[20, 25],
       [ 9,  5]])

In [ ]:
new_arr[:,:,1]

array([[20, 50],
       [ 9,  5],
       [96, 65]])

In [ ]:
new_arr

array([[[10, 20, 25],
        [40, 50, 60]],

       [[ 1,  9,  5],
        [ 4,  5,  6]],

       [[16, 96, 65],
        [64, 65, 66]]])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,10,20,30,40,50,60,70,80,90,100,110,120])
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  10  20  30  40  50  60
  70  80  90 100 110 120]


In [ ]:
arr.reshape(-1)   # 3d array: 2, 2darray: 2 with 3 rows and 2 columns

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  10,
        20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

# Array Indexing

In [ ]:
li = [10,45,34,65,78]

In [ ]:
print(li)

[10, 45, 34, 65, 78]


In [ ]:
print(li[2])
print(li[-3])

34
34


In [ ]:
arr = np.array([12.5,43.6,45.9,56.7])
print(arr)

[12.5 43.6 45.9 56.7]


In [ ]:
print(arr[-2])      #Accessing elements in 1-D array
print(arr[3])

45.9
56.7


In [ ]:
arr = np.array([[12,34,23],[10,20,30]])      #20  23

In [ ]:
print(arr)

[[12 34 23]
 [10 20 30]]


In [ ]:
print(arr[-2,-1])          #[Row in which my element is present, The index of that particular element]

23


In [ ]:
print(arr[-2,-2])

34


In [ ]:
print(arr[-2,0])

12


In [ ]:
li = [30,40,50,10,20]

In [ ]:
li[-4]

40

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[15,20,25]],[[100,200,300],[600,700,800]]])
print(arr)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 15  20  25]]

 [[100 200 300]
  [600 700 800]]]


In [ ]:
print(arr[1,1,1])

20


In [ ]:
# 800
print(arr[2,1,2])

800


In [ ]:
# 5
print(arr[0,1,1])

5


# Array Slicing

In [ ]:
arr = np.array([10.5,23.7,56.4,12.8,34.9,23.9])

In [ ]:
print(arr)

[10.5 23.7 56.4 12.8 34.9 23.9]


In [ ]:
print(arr[2:5])            #[starting index: stopping range(ending index+1)]

[56.4 12.8 34.9]


In [ ]:
print(arr[:3])     #Empty value before : means I am starting from first index
                   #Empty value after : means I will print till last index

[10.5 23.7 56.4]


In [ ]:
print(arr[3:])

[12.8 34.9 23.9]


In [ ]:
print(arr[:])           #No starting index is given and no ending index is given. It will print all the elements

[10.5 23.7 56.4 12.8 34.9 23.9]


In [ ]:
arr = raman.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])   #Slicing in 2d array
print(arr)
#20 30 50 60 80 90

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [ ]:
print(arr[0:2,0:3:2])     #[slicing with row, slicing with elements]   #Step size also we can pass

[[10 30]
 [40 60]]


In [ ]:
# 40 50 70 80
print(arr[1:3,0:2])

[[40 50]
 [70 80]]


In [ ]:
print(arr[0:1])

[[10 20 30]]


In [ ]:
#20 30 50 60 80 90
print(arr[0:3,1:3])

[[20 30]
 [50 60]
 [80 90]]


In [ ]:
arr = np.array([['A','B','C','D','E'],['I','J','K','L','M'],['O','P','Q','R','S'],['T','U','V','W','X']])

In [ ]:
print(arr)

[['A' 'B' 'C' 'D' 'E']
 ['I' 'J' 'K' 'L' 'M']
 ['O' 'P' 'Q' 'R' 'S']
 ['T' 'U' 'V' 'W' 'X']]


In [ ]:
arr[2:,1:4]

array([['P', 'Q', 'R'],
       ['U', 'V', 'W']], dtype='<U1')

In [ ]:
# AB
#IJ
#OP
arr[0:3,0:2]

# P Q R
# U V W

array([['A', 'B'],
       ['I', 'J'],
       ['O', 'P']], dtype='<U1')

In [ ]:
arr[2:4,1:4]

array([['P', 'Q', 'R'],
       ['U', 'V', 'W']], dtype='<U1')

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[14,15,16]],[[17,18,19],[114,115,161]]])

In [ ]:
print(arr)   #Slicing in 3d array

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 14  15  16]]

 [[ 17  18  19]
  [114 115 161]]]


In [ ]:
# 2 3, 8 9, 18 19
arr[:,0,1:3]

array([[ 2,  3],
       [ 8,  9],
       [18, 19]])

In [ ]:
# 5 6
# 15 16
# 115 161
arr[:,1,1:]

array([[  5,   6],
       [ 15,  16],
       [115, 161]])

In [ ]:
import numpy as np   #target = 90
arr = np.array([[[23,45,56],[40,36,15]],[[12,90,89],[45,67,76]]])

In [ ]:
arr[1,0,1]

90

In [ ]:
arr.ndim

3

In [ ]:
arr[1,0,1]

90

# Convert dimensions of array to another

In [ ]:
data = [10,20,30,40,50]            #I can increase the dimensions of my array
arr = np.array(data,ndmin = 8)     #ndmin is used to change the dimensions of your array

In [ ]:
arr

array([[[[[[[[10, 20, 30, 40, 50]]]]]]]])

In [ ]:
arr.ndim

8

In [ ]:
data = np.array([[[23,45,56],[40,36,15]],[[12,90,89],[45,67,76]]])

In [ ]:
data.ndim

3

In [ ]:
arr = np.array(data,ndmin = 2)  #ndmin doesn't reduce your dimensions

In [ ]:
arr

array([[[23, 45, 56],
        [40, 36, 15]],

       [[12, 90, 89],
        [45, 67, 76]]])

In [ ]:
arr_1_d = arr.flatten()    #flatten fxn is used to convert your Nd array into 1d array

In [ ]:
arr_1_d

array([23, 45, 56, 40, 36, 15, 12, 90, 89, 45, 67, 76])

# Convert a 3D array to 2D array

In [ ]:
data_3d = np.array([[[23,45,56],[40,36,15]],[[12,90,89],[45,67,76]]])
data_3d

array([[[23, 45, 56],
        [40, 36, 15]],

       [[12, 90, 89],
        [45, 67, 76]]])

In [ ]:
data_3d.shape    # (2,2,3)   -> 2 -> How many 2d arrays we have

(2, 2, 3)

array([[[23, 45, 56],
        [40, 36, 15]],

       [[12, 90, 89],
        [45, 67, 76]]])   # 12 elements

The size I am converting into should be able to divide my number of elements

2d = [[23,45],[56,40],[36,15],[12,90],[89,45],[67,76]]

2d = [[23,45,56],[40,36,15],[12,90,89],[45,67,76]]

2d = [[23,45,56,40],[36,15,12,90],[89,45,67,76]]

2d = [[23,45,56,40,36],[15,12,90,89,45],[67,76]]  #Error

2d = [[23,45,56,40,36,15],[12,90,89,45,67,76]]

In [ ]:
new_2d = data_3d.reshape(4,-1)  #2,3,4,6 I can use bcz all can divide 12. 12 = number of elements
# -1 is by default parameter and it assigns the dimensions accordingly.

In [ ]:
new_2d

array([[23, 45, 56],
       [40, 36, 15],
       [12, 90, 89],
       [45, 67, 76]])

In [ ]:
new_4d = np.array([[[[10,20],[30,40]],[[100,90],[80,70]]],[[['A','B'],['C','D']],[['E','F'],['G','H']]]])

In [ ]:
new_4d

array([[[['10', '20'],
         ['30', '40']],

        [['100', '90'],
         ['80', '70']]],


       [[['A', 'B'],
         ['C', 'D']],

        [['E', 'F'],
         ['G', 'H']]]], dtype='<U21')

In [ ]:
new_4d.ndim

4

In [ ]:
new_4d = new_4d.reshape(4,4)

array([['10', '20', '30', '40'],
       ['100', '90', '80', '70'],
       ['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U21')

In [ ]:
arr= np.array([1,2,3,4,5,6,7,9,10,8,11,12,13,14,15])

In [ ]:
arr.shape

(15,)

In [ ]:
new_arr = arr.reshape(5,3)    #It should be multiple of the number of elements
                  #rows columns

In [ ]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10],
       [ 8, 11, 12],
       [13, 14, 15]])

In [ ]:
arr = np.array([12,23,43,45,65,76,45,34,23,23,54,65,87,46,12,87,89,54])

In [ ]:
arr

array([12, 23, 43, 45, 65, 76, 45, 34, 23, 23, 54, 65, 87, 46, 12, 87, 89,
       54])

In [ ]:
#one D array to 3d Array
arr.reshape(3,6)                           # 2*3*3
arr_3d = arr.reshape(2,3,3)
arr_3d

array([[[12, 23, 43],
        [45, 65, 76],
        [45, 34, 23]],

       [[23, 54, 65],
        [87, 46, 12],
        [87, 89, 54]]])

# How to generate random numbers using numpy

In [ ]:
import numpy as np

In [ ]:
any = np.random.randint(1,2)    #random integer -> randint (Passing range of elements)
any

1

In [ ]:
import numpy.random as ran

In [ ]:
any_other = np.random.randint(100,102)
any_other

101

# How to generate a random array

In [ ]:
arr = np.random.randint(10,100, size=15)   #size is the number of elements inside our array
arr

array([77, 83, 23, 22, 86, 45, 92, 24, 42, 11, 51, 62, 26, 70, 84])

In [ ]:
arr_2d = arr.reshape(3,5)
arr_2d

array([[71, 16, 42, 83, 93],
       [75, 15, 44, 64, 61],
       [70, 39, 24, 47, 95]])

In [ ]:
#How to generate random float numbers

random_float = np.random.rand()    #Random float values between 0 and 1
random_float

0.3685363896939018

In [ ]:
#How to generate random float numbers between some specific range

random_float = np.random.uniform(10.3,56.8)
rounded_values =  round(random_float,3)
rounded_values

52.163

#Create  a random array with 24 elements then convert it into 2d array and 3d array

In [ ]:
arr_24 =np.random.randint(45,900,size=24)

In [ ]:
arr_24                            #row and columns ->  (4*6)

array([763, 857, 866, 353, 180, 608, 337, 109, 383, 454, 247, 281, 892,
       104, 752, 430, 592, 760, 478,  67, 556, 279, 590, 829])

In [ ]:
#Converting it into 2d array
arr_2d = arr_24.reshape(2,12)             #(2,12)

In [ ]:
#Converting into 3d array

arr_24.reshape(4,3,2)    #(2,6,2)

array([[[763, 857],
        [866, 353],
        [180, 608]],

       [[337, 109],
        [383, 454],
        [247, 281]],

       [[892, 104],
        [752, 430],
        [592, 760]],

       [[478,  67],
        [556, 279],
        [590, 829]]])

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

In [ ]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
for x in arr:
  print(x,end=",")               #end allows us to print in the same line


10,20,30,40,50,60,70,80,90,100,

In [ ]:
li = [10,20,30,40,50]
for x in li:
  print(x)

10
20
30
40
50


In [ ]:
print("HELLO",end=" ")
print("WORLD")

HELLO WORLD


In [ ]:
arr_2d

array([[763, 857, 866, 353, 180, 608, 337, 109, 383, 454, 247, 281],
       [892, 104, 752, 430, 592, 760, 478,  67, 556, 279, 590, 829]])

In [ ]:
for row in arr_2d:
  for ele in row:
    print(ele,end=" ")
  print("Row completed")

763 857 866 353 180 608 337 109 383 454 247 281 Row completed
892 104 752 430 592 760 478 67 556 279 590 829 Row completed


In [ ]:
data_3d = np.array([[[23,45,56],[40,36,15]],[[12,90,89],[45,67,76]]])
data_3d

array([[[23, 45, 56],
        [40, 36, 15]],

       [[12, 90, 89],
        [45, 67, 76]]])

In [ ]:
x = 0
for dim in data_3d:
  print("Dimensions ",x)
  x = x+1
  for row in dim:
    for ele in row:
      print(ele,end=" ")
  print("Finished")


Dimensions  0
23 45 56 40 36 15 Finished
Dimensions  1
12 90 89 45 67 76 Finished


# How to find mean, median of values

In [ ]:
# Mean -> average
# data= [10,7,8,5,4]

#mean = sum of all values/ total number of values
#mean = 10+7+8+5+4/5 -> 6.8
#mean  = 6.8

In [ ]:
data= np.array([10,7,8,5,4])


In [ ]:
avg = np.mean(data)
avg

6.8

In [ ]:
# data = [10,5,4,23,65,78,12,1]
#Sort my data either in ascending or descending order
#sorted = [1,4,5,10,12,23,65,78]
#now look for middle value
#for even number of elements there will be 2 middle values
#[10,12]
#find their avg -> 10+12/2 => 22/2 -> 11 -> MEDIAN

In [ ]:
#Median ->
data = np.array([3,1,20,12,8,6,18,14])
med = np.median(data)
med

10.0

#Mathematical operations with arrays
Make sure your array sizes are same

In [ ]:
arr1 = np.array([10,20,30,40,50])
arr2= np.array([50,60,70,80,90])

In [ ]:
arr_sum = arr1+arr2
arr_sum

mul_arr = arr1*arr2
mul_arr

array([ 500, 1200, 2100, 3200, 4500])

In [ ]:
new_arr = np.concatenate([arr1,arr2])   #inner brackets converting them into list

In [ ]:
new_arr

array([10, 20, 30, 40, 50, 50, 60, 70, 80])

# Create arrays with same numbers

In [ ]:
# I want to create a 2d array of shape (3,4) with all the elements as 5 inside it

In [ ]:
arr = np.full((2,3,4), 43)       #full (size, element)
arr

array([[[43, 43, 43, 43],
        [43, 43, 43, 43],
        [43, 43, 43, 43]],

       [[43, 43, 43, 43],
        [43, 43, 43, 43],
        [43, 43, 43, 43]]])

# Linspace -> It is used to generate numbers between a range

# All values will have equal space between them

In [ ]:
arr  = np.linspace(1,9,20)   #linspace(Range of elements, number of elements)

In [ ]:
arr2 = np.linspace(10,30,50)    # 20% 50  -> 0.4   10 -> 10.4 -> 10.8
arr2

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [ ]:
arr  # 11*5 -> 55 number of elements

array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
       3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
       5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
       7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ])

In [ ]:
arr2

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])